- id: wallet-public-rule
  match:
    url: "http://<.*>/wallet/public/<.*>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  upstream:
    url: "http://localhost:4002"
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: header
      config:
        headers:
          X-Auth-Source: "public"
          X-Auth-Details: "{{ . | toJson }}"

- id: wallet-rule
  match:
    url: "http://<.*>/wallet/<(?!public/).*>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  upstream:
    url: "http://localhost:4002"
  authenticators:
    - handler: oauth2_introspection
      config:
        target_audience:
          - wallet
    - handler: cookie_session
    - handler: bearer_token
  authorizer:
    handler: allow
  mutators:
    - handler: header
      config:
        headers:
          X-Auth-Source: |-
            {{- if and .Extra.identity (eq .Extra.identity.schema_id "normal_users") -}}
              user
            {{- else if .Extra.aud -}}
              {{- $hasMachines := false -}}
              {{- range split " " .Extra.scope -}}
                {{- if eq . "machines" -}}
                  {{- $hasMachines = true -}}
                {{- end -}}
              {{- end -}}
              {{- if $hasMachines -}}
                machines
              {{- else -}}
                user
              {{- end -}}
            {{- else if eq .Subject "public" -}}
              public
            {{- else -}}
              unknown
            {{- end -}}
          X-Auth-Details: "{{ . | toJson }}"

- id: switch-rule
  match:
    url: "http://<.*>/switch/<.*>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  upstream:
    url: "http://localhost:4002"
  authenticators:
    - handler: oauth2_introspection
      config:
        target_audience:
          - switch
  authorizer:
    handler: allow
  mutators:
    - handler: header
      config:
        headers:
          X-Auth-Source: |-
            {{- if .Extra.aud -}}
            {{- $hasMachines := false -}}
            {{- $hasPsp := false -}}
            {{- range split " " .Extra.scope -}}
            {{- if eq . "machines" -}}
            {{- $hasMachines = true -}}
            {{- else if eq . "psp" -}}
            {{- $hasPsp = true -}}
            {{- end -}}
            {{- end -}}
            {{- if $hasMachines -}}
            machines
            {{- else if $hasPsp -}}
            psp
            {{- end -}}
            {{- else -}}
            invalid
            {{- end -}}
          X-Auth-Details: "{{ .Extra | toJson }}"

- id: shared-rule
  match:
    url: "http://<.*>/shared/<.*>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  upstream:
    url: "http://localhost:4002"
  authenticators:
    - handler: oauth2_introspection
      config:
        target_audience:
          - shared
        required_scope:
          - machines
  authorizer:
    handler: allow
  mutators:
    - handler: header
      config:
        headers:
          X-Auth-Details: "{{ .Extra | toJson }}"
          X-Auth-Source: machines

- id: backoffice-rule
  match:
    url: "http://<.*>/backoffice/<.*>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  upstream:
    url: "http://localhost:4002"
  authenticators:
    - handler: oauth2_introspection
      config:
        target_audience:
          - backoffice
    - handler: cookie_session
    - handler: bearer_token
  authorizer:
    handler: allow
  mutators:
    - handler: header
      config:
        headers:
          X-Auth-Source: |-
            {{- if and .Extra.identity (eq .Extra.identity.schema_id "backoffice_users") -}}
            user
            {{- else if .Extra.aud -}}
            {{- $hasMachines := false -}}
            {{- range split " " .Extra.scope -}}
            {{- if eq . "machines" -}}
            {{- $hasMachines = true -}}
            {{- end -}}
            {{- end -}}
            {{- if $hasMachines -}}
            machines
            {{- end -}}
            {{- else -}}
            user
            {{- end -}}
          X-Auth-Details: "{{ .Extra | toJson }}"
